# Generated by Django 6.0 on 2025-12-30 09:36

import django.db.models.deletion
import django_ckeditors.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_booktest_options_alter_callbackrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Australia, United Kingdom', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g., australia, uk)', max_length=100, unique=True)),
                ('tagline', models.CharField(help_text='Subtitle for hero section', max_length=300)),
                ('hero_color_from', models.CharField(default='blue-600', help_text='Start gradient color (e.g., blue-600)', max_length=50)),
                ('hero_color_via', models.CharField(default='blue-700', help_text='Middle gradient color (e.g., blue-700)', max_length=50)),
                ('hero_color_to', models.CharField(default='indigo-800', help_text='End gradient color (e.g., indigo-800)', max_length=50)),
                ('universities_count', models.CharField(help_text='e.g., 43, 130+', max_length=50)),
                ('work_rights_duration', models.CharField(help_text='e.g., 2-4 Yrs', max_length=50)),
                ('work_hours_limit', models.CharField(help_text='e.g., 48h, 20h/week', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destinations/hero/')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('featured', models.BooleanField(default=False, help_text='Featured destination')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('why_study', 'Why Study Here'), ('visa_requirements', 'Visa Requirements'), ('cost', 'Cost of Studying'), ('scholarships', 'Scholarships'), ('intakes', 'Intakes'), ('language_requirements', 'Language Requirements (IELTS/PTE)'), ('top_courses', 'Top Courses'), ('top_universities', 'Top Universities'), ('job_prospects', 'Job Prospects'), ('living_costs', 'Cost of Living'), ('accommodation', 'Accommodation Options'), ('culture', 'Culture & Lifestyle'), ('application_process', 'Application Process'), ('faqs', 'FAQs'), ('custom', 'Custom Section')], max_length=50)),
                ('title', models.CharField(help_text='Section heading', max_length=200)),
                ('icon', models.CharField(default='fa-globe', help_text='FontAwesome icon (e.g., fa-globe, fa-passport)', max_length=50)),
                ('color_from', models.CharField(default='blue-500', help_text='Badge gradient start (e.g., blue-500)', max_length=50)),
                ('color_to', models.CharField(default='indigo-600', help_text='Badge gradient end (e.g., indigo-600)', max_length=50)),
                ('content', django_ckeditors.fields.CKEditorsField(blank=True, help_text='Main section content (HTML allowed)')),
                ('show_bullet_points', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Section order')),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.destination')),
            ],
            options={
                'verbose_name': 'Destination Section',
                'verbose_name_plural': 'Destination Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Bullet point content')),
                ('icon', models.CharField(default='fa-check-circle', help_text='FontAwesome icon (e.g., fa-check-circle)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='web.destinationsection')),
            ],
            options={
                'verbose_name': 'Bullet Point',
                'verbose_name_plural': 'Bullet Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g., World-class education', max_length=100)),
                ('icon', models.CharField(default='fa-check-circle', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_highlights', to='web.destination')),
            ],
            options={
                'verbose_name': 'Hero Highlight',
                'verbose_name_plural': 'Hero Highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Stat label (e.g., Tuition Fees)', max_length=100)),
                ('value', models.CharField(help_text='Stat value (e.g., AUD 20K-45K)', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Small text below value (e.g., Per year)', max_length=200)),
                ('icon', models.CharField(default='fa-info-circle', help_text='FontAwesome icon', max_length=50)),
                ('color', models.CharField(default='blue-600', help_text='Color theme (e.g., blue-600, green-600)', max_length=50)),
                ('column_span', models.IntegerField(choices=[(1, '1 Column'), (2, '2 Columns')], default=1, help_text='Grid column span')),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='web.destinationsection')),
            ],
            options={
                'verbose_name': 'Section Stat',
                'verbose_name_plural': 'Section Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('icon', models.CharField(default='fa-graduation-cap', max_length=50)),
                ('color', models.CharField(default='blue-600', help_text='Background color (e.g., blue-50)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_courses', to='web.destination')),
            ],
            options={
                'verbose_name': 'Top Course',
                'verbose_name_plural': 'Top Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='destinations/universities/')),
                ('ranking', models.CharField(blank=True, help_text='e.g., #1 in Australia', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('color', models.CharField(default='blue-600', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_universities', to='web.destination')),
            ],
            options={
                'verbose_name': 'Top University',
                'verbose_name_plural': 'Top Universities',
                'ordering': ['order'],
            },
        ),
    ]
