# Generated by Django 6.0 on 2025-12-31 10:21

import django.db.models.deletion
import django_ckeditors.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_destination_destinationsection_bulletpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Study Abroad Tips, Visa Guide', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='blue-600', help_text='Category color (e.g., blue-600)', max_length=50)),
                ('icon', models.CharField(default='fa-folder', help_text='FontAwesome icon', max_length=50)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='destinationsection',
            name='show_mini_cards',
            field=models.BooleanField(default=False, help_text='Show mini info cards'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listings', max_length=300)),
                ('content', django_ckeditors.fields.CKEditorsField(help_text='Main blog content (HTML allowed)')),
                ('featured_image', models.ImageField(help_text='Main image for the post', upload_to='blog/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for SEO', max_length=200)),
                ('author_name', models.CharField(default='Admin', max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('author_bio', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, help_text='Date to publish (can be future)', null=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of views')),
                ('reading_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_trending', models.BooleanField(default=False, help_text='Show in trending section')),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='web.blogcategory')),
                ('related_destination', models.ForeignKey(blank=True, help_text='Link to a destination if relevant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='web.destination')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='web.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Approve comment to show publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card title (e.g., Student Visa)', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Small text below title (e.g., Subclass 500)', max_length=150)),
                ('description', models.TextField(help_text='Card description (2-3 lines)')),
                ('icon', models.CharField(default='fa-info-circle', help_text='FontAwesome icon', max_length=50)),
                ('bg_color', models.CharField(default='blue-50', help_text='Background color (e.g., blue-50, green-50)', max_length=50)),
                ('icon_color', models.CharField(default='blue-600', help_text='Icon color (e.g., blue-600)', max_length=50)),
                ('border_color', models.CharField(default='blue-200', help_text='Border color (e.g., blue-200)', max_length=50)),
                ('link_text', models.CharField(blank=True, help_text='Link text (e.g., Learn More)', max_length=50)),
                ('link_url', models.URLField(blank=True, help_text='External link URL')),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_cards', to='web.destinationsection')),
            ],
            options={
                'verbose_name': 'Mini Card',
                'verbose_name_plural': 'Mini Cards',
                'ordering': ['order'],
            },
        ),
    ]
