# Generated by Django 6.0 on 2026-02-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blogcategory_blogtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingappointment',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
