# Generated by Django 6.0 on 2026-02-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_counsellingappointment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('quote', models.TextField()),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('intake', models.CharField(max_length=100)),
                ('border_color', models.CharField(default='border-blue-500', max_length=50)),
                ('text_color', models.CharField(default='text-blue-700 dark:text-blue-300', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
