# Generated by Django 6.0 on 2026-02-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingappointment',
            name='counselling_mode',
            field=models.CharField(choices=[('online', 'Online (Video Call)'), ('in_person', 'In-Person Visit'), ('phone', 'Phone Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='counsellingappointment',
            name='current_academic_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's"), ('masters', "Master's")], max_length=50),
        ),
        migrations.AlterField(
            model_name='counsellingappointment',
            name='intended_academic_level',
            field=models.CharField(choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='counsellingappointment',
            name='preferred_destination',
            field=models.CharField(choices=[('Australia', 'Australia'), ('Canada', 'Canada'), ('UK', 'UK'), ('USA', 'USA'), ('Germany', 'Germany'), ('New Zealand', 'New Zealand'), ('France', 'France'), ('Other', 'Other')], max_length=50),
        ),
    ]
