# Generated by Django 5.2.7 on 2025-11-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('test_type', models.CharField(choices=[('IELTS Academic', 'IELTS Academic'), ('IELTS CBT', 'IELTS CBT'), ('IELTS UKVI', 'IELTS UKVI'), ('IELTS General', 'IELTS General'), ('PTE Academic', 'PTE Academic'), ('PTE Academic UKVI', 'PTE Academic UKVI'), ('PTE Core', 'PTE Core'), ('OET', 'OET'), ('Duolingo Test', 'Duolingo Test')], max_length=50)),
                ('test_mode', models.CharField(max_length=50)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('preferred_destination', models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('UK', 'UK'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Germany', 'Germany'), ('France', 'France'), ('Other', 'Other')], max_length=50)),
                ('intended_academic_level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=50)),
                ('current_academic_level', models.CharField(choices=[('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50)),
                ('counselling_mode', models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online')], max_length=20)),
                ('accept_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
