# Generated by Django 5.2.7 on 2025-12-04 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Book Tests'},
        ),
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Callback Requests'},
        ),
        migrations.AlterModelOptions(
            name='counsellingappointment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Counselling Appointments'},
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booktest',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='booktest',
            name='test_mode',
            field=models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online')], max_length=50),
        ),
        migrations.AlterField(
            model_name='counsellingappointment',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
